### PR TITLE
Dtportal 19264 static analysis php 74

### PR DESCRIPTION
**Pull request by gfaza**
Zend Framework 1 reaches its End of Life (EOL) and is no longer maintained.
No Pull Requests will be accepted.

https://framework.zend.com/blog/2016-06-28-zf1-eol.html

This PR is composed of the following changes:
* Pulling shardj/zf1-future changes, purported to be PHP 7.4 compatible.
* Adding alerts for remaining PHP 7.4 compatibility issues in order to detect whether we use any of that framework code in our applications.
* Adding PHP 7.4 to the travis build.

Beyond pulling the most recent changes from shardj, the diff is composed only of https://github.com/cloudvox/zf1-future/compare/9c6672cd500a028088df4a9127662c9dbc497890..a3942189468508c0cc1d25130c77a7c2d4bc0cc3

### CODE REVIEW

**Comment by gfaza** [comment]
@abhishek-algoworks please try using this branch (gfaza:DTPORTAL-19264-static_analysis_php_74) in your attempts at getting the sandbox to use PHP 7.4, and let me know how it goes, in case i can help get that working.

**Comment by abhishek-algoworks** [comment]
@gfaza This is great. I just ran an updated unit test on php7.4 and no deprecation warnings were thrown. Earlier it would just give
```
[PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /docker/Organic/vendor/shardj/zf1-future/library/Zend/Registry.php on line 206]
```
Draft PR https://github.com/cloudvox/Organic/pull/2199

**Comment by gfaza** [comment]
@yadnad, if you please!

**Review by yadnad — APPROVED** [review]
The diff of Frederic's changes looks good to go.

**Comment by gfaza** [comment]
@mattcar do you remember what the process is for this library?  merge into `develop` then bump all composer.json files that reference it?  if so, who bumps them?

**Comment by mattcar** [comment]
@gfaza that is indeed the process. I can, you can, doesn't matter to me.

**Comment by gfaza** [comment]
@mattcar could you point me at the steps you'd use to bump the composer.json files, after this PR is merged?  I'm guessing a sequence of

1. `git checkout develop ; git pull ; git checkout -b DTPORTAL-19264-bumping_composer_json`
1. some variation on `/usr/bin/php ./bin/composer.phar update shardj/zf1-future` ... please correct me as necessary ... I'm not confident that old cmd will work with the dockerized sandbox ...
1. `git commit -am 'DTPORTAL-19264 bumping composer.json' ; git push origin HEAD`

**then**

1. Merge change to secure-dev (or equivalent) and deploy to DEV.
1. Assuming all's well, then open a PR for the particular app

**Comment by gfaza** [comment]
i'll gladly take you up on the offer @mattcar, to bump those consuming apps, sir! 🙏

**Comment by mattcar** [comment]
I've found this dependency referenced in the following repositories:
- integrations-adobe-media-optimizer
- integrations-marin
- Ifbyphone
- CRBN
- Organic


@gfaza @yadnad can you confirm if this update needs to be applied to all or a subset of the above?

**Comment by mattcar** [comment]
@gfaza this is what has worked for me:
`./bin/composer.phar --no-progress --no-interaction --no-ansi --verbose update shardj/zf1-future`

**Comment by yadnad** [comment]
> I've found this dependency referenced in the following repositories:
> 
> * integrations-adobe-media-optimizer
> * integrations-marin
> * Ifbyphone
> * CRBN
> * Organic
> 
> @gfaza @yadnad can you confirm if this update needs to be applied to all or a subset of the above?

that's all I'm seeing in Github as well

**Comment by gfaza** [comment]
> I've found this dependency referenced in the following repositories:
> 
> * integrations-adobe-media-optimizer
> * integrations-marin
> * Ifbyphone
> * CRBN
> * Organic
> 
> @gfaza @yadnad can you confirm if this update needs to be applied to all or a subset of the above?

should be to all, though i'm only hearing of those `integrations-*` apps for the first time.  perhaps to Ifbyphone prior than to CRBN and Organic?  unsure - but the order may matter there.

**Comment by mattcar** [comment]
@gfaza @yadnad @mikeheidenreich i think we'll need to cut individual cards for each repo update and ensure tester availability before proceeding

**Pull request merged**
