### PR TITLE
DTPORTAL-19297 Set samesite Attributes in Cookies

### PR DESCRIPTION
**Pull request by abhishek-algoworks**
## [Set samesite Attributes in Cookies](https://dialogtech.atlassian.net/browse/DTPORTAL-19297)
Remove same-site functionality from code and add the `session.cookie_samesite = "None"` to php.ini file.

### Requires
* https://dialogtech.atlassian.net/browse/TECHOPS-5509
* PHP7.4

### Code Reviewers
@BMTTMC @tdupreeibp @gfaza

### CODE REVIEW

**Comment by BMTTMC** [comment]
This looks good to me, but please link the ticket for adjusting the INI file.  We need to make sure that gets out before this is merged.

**Comment by abhishek-algoworks** [comment]
> This looks good to me, but please link the ticket for adjusting the INI file. We need to make sure that gets out before this is merged.

Added the required TechOps ticket to description.

**Comment by mattcar** [comment]
@abhishek-algoworks which repos does this update need to be applied to? do we know the status of the techops work?

**Comment by abhishek-algoworks** [comment]
> @abhishek-algoworks which repos does this update need to be applied to? do we know the status of the techops work?

This work is only required for CRBN. However, this should only be deployed to PHP7.4. I've added the same to the story and updated the requirement above.

**Review by BMTTMC — APPROVED** [review]
This code looks good.  Having said that, @tdupreeibp: please feel free to weigh in.
@mattcar 👍

**Pull request merged**
